#!/usr/bin/env perl
# Copyright (c) 2016-2023 The Hush developers
# Released under the GPLv3

use strict;
use warnings;

my $x = 340_000;
my $n = 0;
my $r = 12_500_000_000;
while ($n<=32) {
    printf "%d,%d,%d\n", $n+1, $r, $x + 1680000*$n;
    # blocktime halving at block 340000
    if ($n==0) {
        $r = 3.125 * 100_000_000;
    } else {
        $r /= 2;
    }

    $n++;
}

