#!/usr/bin/env bash
# Copyright (c) 2018-2023 The Hush developers
#set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

../hush-cli $@
