// Copyright (c) 2016-2023 The Hush developers
// Distributed under the GPLv3 software license, see the accompanying
// file COPYING or https://www.gnu.org/licenses/gpl-3.0.en.html
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY DIRECTLY
// Instead, update contrib/seeds/nodes_main.txt then run
//    ./contrib/seeds/generate-seeds.py contrib/seeds > src/chainparamsseeds.h
// OR run: make seeds
#ifndef HUSH_CHAINPARAMSSEEDS_H
#define HUSH_CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the Hush network
// Each line contains a BIP155 serialized address.
//
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xb9,0xf1,0x5d,0x2b,0x00,0x00,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x01,0x02,0x03,0x04,0x00,0x00, // 1.2.3.4
};
#endif // HUSH_CHAINPARAMSSEEDS_H
