#!/usr/bin/env bash
# Copyright (c) 2016-2023 The Hush developers
# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

DEFAULTS=""

# People can just use hushd going forward, but this script makes it
# more clear what is going on
HUSH="./hushd"
$HUSH $DEFAULTS "$@"
