#!/usr/bin/env bash
# Copyright (c) 2018-2023 The Hush developers
set -eo pipefail

# You can now add delay line to pubkey.txt file
source pubkey.txt
overide_args="$@"
seed_ip=$(SEEDNODE)
hsc='./hush-smart-chain'

if [ -z "$delay" ]; then delay=20; fi

./listassetchainparams | while read args; do
  gen=""
  if [ $[RANDOM % 10] == 1 ]; then
      gen=" -gen -genproclimit=1"
  fi

  $hsc $gen $args $overide_args -pubkey=$pubkey -addnode=$seed_ip &
  sleep $delay
done
