#!/usr/bin/env bash
# Copyright 2016-2023 The Hush Developers
# Copyright 2022      The DragonX Developers
# Released under the GPLv3

# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

./hush-cli -ac_name=TESTEQUIHASH $@
