#!/usr/bin/env bash
# Copyright (c) 2016-2023 The Hush developers

# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=TUSH

# Use the HUSHCLI env var to over-ride using the same directory as this file
CLI=${HUSHCLI:-./hush-cli}
if [ -f $CLI ]; then
   $CLI -ac_name=$NAME "$@"
fi
