#!/usr/bin/env bash
# Copyright 2016-2023 The Hush Developers
# Copyright 2023      The ZDEEX Developers
# Released under the GPLv3

# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR


# Remember Remember the 5th November for freedom of speech is not free!!
./hush-smart-chain -ac_name=ZDEEX -ac_sapling=1 -ac_reward=200000000 -ac_blocktime=300 -ac_cc=2 -ac_founders=1 -ac_perc=10000000 -ac_halving=1000000 -ac_supply=100000 -ac_private=1 -addnode=node.zdeex.org -addnode=node1.zdeex.org -addnode=node2.zdeex.org -ac_pubkey=03abd1d20f8c7cf579d80788c1d4d23fcb10b04a4f01f43d2bf0aac6a51b05db0e $@

